//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngHealthyGarden
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddressInfo()
        {
            this.CustomerInfoes = new HashSet<CustomerInfo>();
        }
    
        public int AddressInfoId { get; set; }
        public string Street { get; set; }
        public string Apartment { get; set; }
        public int ZipId { get; set; }
    
        public virtual ZipCode ZipCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerInfo> CustomerInfoes { get; set; }
    }
}
