//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngHealthyGarden
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public int DishId { get; set; }
        public string DishName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Picture { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> SideId { get; set; }
        public Nullable<int> TortillaId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Side Side { get; set; }
        public virtual Size Size { get; set; }
        public virtual TortillaType TortillaType { get; set; }
    }
}
