//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngHealthyGarden
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailId { get; set; }
        public int DishId { get; set; }
        public Nullable<int> SideId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> OptionId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int CustomerInfoId { get; set; }
        public int OrderTypeId { get; set; }
        public int RestaurantId { get; set; }
        public Nullable<int> CommentId { get; set; }
        public int OrderId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual CustomerInfo CustomerInfo { get; set; }
        public virtual Dish Dish { get; set; }
        public virtual Option Option { get; set; }
        public virtual Order Order { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual Side Side { get; set; }
        public virtual Size Size { get; set; }
    }
}
